app_name = "digicomply"
app_title = "DigiComply"
app_publisher = "DigiComply"
app_description = "UAE E-Invoicing Compliance & Reconciliation Platform"
app_email = "hello@digicomply.ae"
app_license = "MIT"
app_version = "1.0.0"

# Branding - Complete White-Label
brand_html = """
<div style="display:flex;align-items:center;gap:8px;">
    <svg width="24" height="24" viewBox="0 0 32 32" fill="none">
        <path d="M9 16 L13 20 L23 10" stroke="#a404e4" stroke-width="3" fill="none"/>
    </svg>
    <span style="font-weight:700;color:#1e293b;">DigiComply</span>
</div>
"""

# App Logo
app_logo_url = "/assets/digicomply/images/logo.png"

# Required Apps
required_apps = ["frappe"]

# App Includes (must be lists)
app_include_css = ["/assets/digicomply/css/digicomply.css"]
app_include_js = ["/assets/digicomply/js/digicomply.js"]

# Website Route Rules
website_route_rules = [
    {"from_route": "/setup-wizard", "to_route": "digicomply-setup"},
]

# Remove home_page override - let users land on workspace then navigate to dashboard

# Override standard pages
page_js = {
    "setup-wizard": "public/js/setup_wizard_override.js"
}

# Website context
website_context = {
    "favicon": "/assets/digicomply/images/favicon.svg",
    "splash_image": "/assets/digicomply/images/logo-full.svg"
}

# Boot Session
boot_session = "digicomply.boot.boot_session"

# Desk Notifications
notification_config = "digicomply.notifications.get_notification_config"

# DocType Events
doc_events = {
    "Reconciliation Run": {
        "on_submit": "digicomply.digicomply.doctype.reconciliation_run.reconciliation_run.on_submit_handler",
    },
    "Sales Invoice": {
        "on_submit": "digicomply.digicomply.doctype.e_invoice.e_invoice.auto_create_e_invoice",
    },
    # CSV Import processes automatically in validate()
}

# Scheduled Tasks
scheduler_events = {
    "daily": [
        "digicomply.reconciliation.tasks.check_pending_reconciliations",
        "digicomply.digicomply.doctype.auditor_access.auditor_access.check_expired_access",
        "digicomply.digicomply.doctype.report_schedule.report_schedule.run_scheduled_reports",
    ],
    "weekly": [
        "digicomply.reconciliation.tasks.generate_weekly_summary",
    ],
}

# Fixtures - Export on install
fixtures = [
    {
        "dt": "Custom Field",
        "filters": [["module", "=", "DigiComply"]],
    },
    {
        "dt": "Property Setter",
        "filters": [["module", "=", "DigiComply"]],
    },
    {
        "dt": "Invoice Type Code",
    },
    {
        "dt": "Tax Category Code",
    },
    {
        "dt": "Role",
        "filters": [["is_custom", "=", 1], ["role_name", "like", "%DigiComply%"]],
    },
    {
        "dt": "Role",
        "filters": [["role_name", "in", ["Compliance Manager", "Company Accountant", "Company Reviewer", "External Auditor", "API User"]]],
    },
]

# Jinja Environment
jenv = {
    "methods": [
        "digicomply.utils.format_trn:format_trn",
        "digicomply.utils.format_aed:format_aed",
    ],
}

# Installation
after_install = "digicomply.setup.install.after_install"
before_uninstall = "digicomply.setup.install.before_uninstall"

# Migration
after_migrate = "digicomply.setup.install.after_migrate"

# Permissions
has_permission = {
    "Reconciliation Run": "digicomply.digicomply.doctype.reconciliation_run.reconciliation_run.has_permission",
}

# Document Naming
naming_rule = {
    "Reconciliation Run": "REC-.YYYY.-.#####",
    "Reconciliation Item": "REC-ITEM-.YYYY.-.#####",
    "CSV Import": "CSV-.YYYY.-.#####",
    "Mismatch Report": "MIS-.YYYY.-.#####",
}

# Default Print Formats
default_print_formats = {
    "Mismatch Report": "Mismatch Report PDF",
}

# Email Templates - Custom branded templates
email_brand_image = "/assets/digicomply/images/logo.png"
default_mail_footer = """
<div style="margin-top:24px;padding-top:16px;border-top:1px solid #e2e8f0;text-align:center;color:#94a3b8;font-size:12px;">
    <p style="margin:0;">DigiComply - UAE E-Invoicing Compliance Platform</p>
    <p style="margin:4px 0 0 0;"><a href="mailto:support@digicomply.ae" style="color:#a404e4;">support@digicomply.ae</a></p>
</div>
"""

# Override standard templates
email_templates = {
    "standard": "templates/emails/standard_email.html",
}

# Standard Reply Configuration
standard_reply = {
    "email_account": "noreply@digicomply.ae",
    "sender_name": "DigiComply",
}

# PDF Settings - Custom footer
pdf_page_settings = {
    "footer_html": """
        <div style="text-align:center;font-size:10px;color:#94a3b8;padding:8px;">
            Generated by DigiComply - UAE E-Invoicing Compliance Platform
        </div>
    """
}

# Website Settings Override (ensures no Frappe branding leaks)
website_settings = {
    "app_name": "DigiComply",
    "brand_html": brand_html,
    "copyright": "DigiComply",
    "disable_signup": 0,
    "home_page": "login",
}
